### ISSUE TITLE
Issue with GitHub points

### ISSUE THREAD

**Issue by masterdesky** [qati/DeepLearningCourse#5]
I'm still not on the points list, however I uploaded all the homeworks with the correct names, didn't change function names, etc. Also checked that I've registered the correct Github and Kaggle usernames.
Where's the problem?
(Yes, my programs works well too, and prints the expected outputs everywhere)

**Comment by qati** [comment]
Please update the first notebook (https://github.com/masterdesky/DeepLearningCourse/blob/master/assignments/hw01_numpy_solved.ipynb) because it's not valid jupyter notebook. If it is valid, then github will be able to render it. If you try to open it now, you just got an error message: "Sorry, something went wrong. Reload?"

**Comment by masterdesky** [comment]
Okay, I updated it. In the .ipynb file's raw version, there was some missing " after a couple of new lines. Now all of them should work, because I don't get the "something went wrong" error in GitHub now, neither the JSON syntax error in the Notebook.

**Comment by qati** [comment]
You points in the list now!
